Changed bspwm style to compact. Added some other fixes and minor changes

diff --git a/dotfiles/.config/bspwm/bspwmrc b/dotfiles/.config/bspwm/bspwmrc
--- a/dotfiles/.config/bspwm/bspwmrc
+++ b/dotfiles/.config/bspwm/bspwmrc
@@ -3,25 +3,25 @@
 ###
 ### Geometry
 ###
-bspc config window_gap		10
-bspc config top_padding		40
-bspc config left_padding	8
-bspc config right_padding	8
-bspc config bottom_padding	5
-bspc config border_width	7
+bspc config window_gap		0
+bspc config top_padding		30
+bspc config left_padding	0
+bspc config right_padding	0
+bspc config bottom_padding	0
+bspc config border_width	0
 
 ###
 ### Colors
 ###
-if [ -f "${XDG_CACHE_HOME}/wal/colors.sh" ]; then
-    . "${XDG_CACHE_HOME}/wal/colors.sh"
+if [ -f "${XDG_CACHE_HOME:=~/.cache}/wal/colors.sh" ]; then
+    . "${XDG_CACHE_HOME:=~/.cache}/wal/colors.sh"
 else
-    echo "Couldn't find wal generated theme" >&2
+    echo "Couldn't find wal generated theme at ${XDG_CACHE_HOME:=~/.cache}/wal/colors.sh" >&2
 fi
-bspc config normal_border_color		"${background:=#262424}" #$(getcolhex bg) #$background #"#262424"
-bspc config focused_border_color	"${color4:=#0076FF}" #$(getcolhex blue) #$color0 #"#0076FF"
-bspc config active_border_color     "${color12:=#00A0FF}" #(getcolhex lblue)
-bspc config presel_feedback_color	"${color7:=#302e2e}" #$(getcolhex gray) #$color7 #"#302e2e"
+bspc config normal_border_color		"${background:=#262424}"
+bspc config focused_border_color	"${color4:=#0076FF}"
+bspc config active_border_color     "${color12:=#00A0FF}"
+bspc config presel_feedback_color	"${color7:=#302e2e}"
 
 ###
 ### Various settings
@@ -34,7 +34,7 @@ bspc config single_monocle      true
 #bspc config initial_polarity second_child
 bspc config remove_disabled_monitors true
 bspc config remove_unplugged_monitors true
-bspc config honor_size_hints true 
+bspc config honor_size_hints false # urxvt tries to increment only by font character dimensions
 bspc config focus_follows_pointer true
 #bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting
 bspc config split_ratio         0.5
