Hooked up bspwm and rofi with wal generated color scheme (as well as vscode and jetbrains IDEs)

diff --git a/dotfiles/.config/bspwm/bspwmrc b/dotfiles/.config/bspwm/bspwmrc
--- a/dotfiles/.config/bspwm/bspwmrc
+++ b/dotfiles/.config/bspwm/bspwmrc
@@ -13,10 +13,15 @@ bspc config border_width	7
 ###
 ### Colors
 ###
-bspc config normal_border_color		"#262424" #$(getcolhex bg) #$background #"#262424"
-bspc config focused_border_color	"#0076FF" #$(getcolhex blue) #$color0 #"#0076FF"
-#bspc active_border_color		$(getcolhex lblue)
-bspc config presel_feedback_color	"#302e2e" #$(getcolhex gray) #$color7 #"#302e2e"
+if [ -f "${XDG_CACHE_HOME}/wal/colors.sh" ]; then
+    . "${XDG_CACHE_HOME}/wal/colors.sh"
+else
+    echo "Couldn't find wal generated theme" >&2
+fi
+bspc config normal_border_color		"${background:=#262424}" #$(getcolhex bg) #$background #"#262424"
+bspc config focused_border_color	"${color4:=#0076FF}" #$(getcolhex blue) #$color0 #"#0076FF"
+bspc config active_border_color     "${color12:=#00A0FF}" #(getcolhex lblue)
+bspc config presel_feedback_color	"${color7:=#302e2e}" #$(getcolhex gray) #$color7 #"#302e2e"
 
 ###
 ### Various settings
